language: bash
dist: trusty
sudo: required

before_install:
    - sudo apt-get update -q
    - sudo apt-get install -y git make build-essential clang libboost-all-dev cmake unzip libblas-dev liblapack-dev libatlas-base-dev gfortran
    - sudo pip install -U nltk
    - sudo pip install -U numpy
    - sudo pip install -U scipy
    - sudo pip install -U gensim

script: 
    - bash ./webserver/tests/prerequisites.sh
    - bash ./webserver/tests/unbound2plain.sh
    - bash ./webserver/tests/my_tokenizer.sh
    - bash ./webserver/tests/train.sh
notifications:
  slack: wycliffe-rtt:VUrvcEm1aT1oBNzxUalH6Zxf